spring:
  datasource:
    url: jdbc:postgresql://172.18.0.1:5432/
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
